// Generated by gencpp from file stm_interface/RelayControlRequest.msg
// DO NOT EDIT!


#ifndef STM_INTERFACE_MESSAGE_RELAYCONTROLREQUEST_H
#define STM_INTERFACE_MESSAGE_RELAYCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stm_interface
{
template <class ContainerAllocator>
struct RelayControlRequest_
{
  typedef RelayControlRequest_<ContainerAllocator> Type;

  RelayControlRequest_()
    : data(0)  {
    }
  RelayControlRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::stm_interface::RelayControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stm_interface::RelayControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelayControlRequest_

typedef ::stm_interface::RelayControlRequest_<std::allocator<void> > RelayControlRequest;

typedef boost::shared_ptr< ::stm_interface::RelayControlRequest > RelayControlRequestPtr;
typedef boost::shared_ptr< ::stm_interface::RelayControlRequest const> RelayControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stm_interface::RelayControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stm_interface::RelayControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stm_interface::RelayControlRequest_<ContainerAllocator1> & lhs, const ::stm_interface::RelayControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stm_interface::RelayControlRequest_<ContainerAllocator1> & lhs, const ::stm_interface::RelayControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stm_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stm_interface::RelayControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stm_interface::RelayControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stm_interface::RelayControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c8164229e7d2c17eb95e9231617fdee";
  }

  static const char* value(const ::stm_interface::RelayControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c8164229e7d2c17ULL;
  static const uint64_t static_value2 = 0xeb95e9231617fdeeULL;
};

template<class ContainerAllocator>
struct DataType< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stm_interface/RelayControlRequest";
  }

  static const char* value(const ::stm_interface::RelayControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 data\n"
;
  }

  static const char* value(const ::stm_interface::RelayControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stm_interface::RelayControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stm_interface::RelayControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STM_INTERFACE_MESSAGE_RELAYCONTROLREQUEST_H
