// Generated by gencpp from file stm_interface/RelayControl.msg
// DO NOT EDIT!


#ifndef STM_INTERFACE_MESSAGE_RELAYCONTROL_H
#define STM_INTERFACE_MESSAGE_RELAYCONTROL_H

#include <ros/service_traits.h>


#include <stm_interface/RelayControlRequest.h>
#include <stm_interface/RelayControlResponse.h>


namespace stm_interface
{

struct RelayControl
{

typedef RelayControlRequest Request;
typedef RelayControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelayControl
} // namespace stm_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stm_interface::RelayControl > {
  static const char* value()
  {
    return "6db4585f5f37e5eeadda4ec7286a1620";
  }

  static const char* value(const ::stm_interface::RelayControl&) { return value(); }
};

template<>
struct DataType< ::stm_interface::RelayControl > {
  static const char* value()
  {
    return "stm_interface/RelayControl";
  }

  static const char* value(const ::stm_interface::RelayControl&) { return value(); }
};


// service_traits::MD5Sum< ::stm_interface::RelayControlRequest> should match
// service_traits::MD5Sum< ::stm_interface::RelayControl >
template<>
struct MD5Sum< ::stm_interface::RelayControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stm_interface::RelayControl >::value();
  }
  static const char* value(const ::stm_interface::RelayControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stm_interface::RelayControlRequest> should match
// service_traits::DataType< ::stm_interface::RelayControl >
template<>
struct DataType< ::stm_interface::RelayControlRequest>
{
  static const char* value()
  {
    return DataType< ::stm_interface::RelayControl >::value();
  }
  static const char* value(const ::stm_interface::RelayControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stm_interface::RelayControlResponse> should match
// service_traits::MD5Sum< ::stm_interface::RelayControl >
template<>
struct MD5Sum< ::stm_interface::RelayControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stm_interface::RelayControl >::value();
  }
  static const char* value(const ::stm_interface::RelayControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stm_interface::RelayControlResponse> should match
// service_traits::DataType< ::stm_interface::RelayControl >
template<>
struct DataType< ::stm_interface::RelayControlResponse>
{
  static const char* value()
  {
    return DataType< ::stm_interface::RelayControl >::value();
  }
  static const char* value(const ::stm_interface::RelayControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STM_INTERFACE_MESSAGE_RELAYCONTROL_H
